flowchart LR
    lead_engaged_comment --> personalized_message
    lead_engaged_comment --> used_social_proof
    personalized_message --> lead_engaged_comment
    personalized_message --> used_social_proof
    used_social_proof --> lead_engaged_comment
    used_social_proof --> personalized_message